sudo: reqiured
dist: trusty

language: python

python:
  - "3.5"

before_install:
  - pip install -r requirements.txt
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended

install:
  - python main.py

script:
  - find . -name "all.pdf"