sudo: reqiured
dist: trusty

language: python
env:
  - LATEX_PACKAGES="texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-base texlive-bibtex-extra texlive-extra-utils texlive-font-utils texlive-binaries texlive-generic-extra texlive-generic-recommended texlive-lang-cyrillic texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-luatex texlive-math-extra texlive-pictures texlive-pstricks texlive-science texlive-xetex"

python:
  - "3.5"

before_install:
  - pip install -r requirements.txt
  - sudo apt-get -qq update && sudo apt-get install -y $LATEX_PACKAGES

install:
  - python main.py

after_failure:
  # Будем собирать до победного конца!
  - python main.py

script:
  - find . -name "all.pdf"

before_deploy:
  - git config --local user.name "alekseik1"
  - git config --local user.email "alekseik1@yandex.ru"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  skip-cleanup: true
  api_key: $GITHUB_TOKEN
  file: "all.pdf"
  overwrite: true
  on:
    tags: true